### ISSUE TITLE
[Passives export - 3.16] Add parsing for masteries

### ISSUE THREAD

**Issue by Journeytojah** [Project-Path-of-Exile-Wiki/PyPoE#30]
We need to add parsing and wiki templating for the masteries.

**Comment by angelic-knight** [comment]
Most of the parsing is the same as standard passive skill parsing.
For the ones I spot checked, it isn't generating stat_text for them.
This is probably because their list of stats aren't stored in the passives table like they are for most other passives.
Instead, they're mapped to MasteryGroups and then MasteryEffects have their actual stats in them.
I'm not finding a mapping between MasteryEffects and individual passives, but that probably doesn't matter too much since they're indistinguishable to the player.

**Comment by angelic-knight** [comment]
Gave this some more thought.
I think the parsing that was done by `passives` is just for the nodes on the passive tree that you can click on, and are linked to the notables. I'm pretty sure there shouldn't be any mapping between these and the individual mastery options. They aren't linked until you pick one of the mastery options in game.

I think we need to separately parse MasteryEffects and MasteryGroups to pull the options and stat texts.

This is less essential, but we should also add a column in cargo that maps passives to groups so we can easily tell how many options within a mastery you can get.

**Comment by angelic-knight** [comment]
I've started some work on this in https://github.com/angelic-knight/PyPoE/tree/patches-masteries
