### ISSUE TITLE
Error when exporting Currency Cyclone Effect

### ISSUE THREAD

**Issue by acbeaumo** [Project-Path-of-Exile-Wiki/PyPoE#49]
For some reason I get an error when trying to export the Currency Cyclone Effect. This error doesn't appear when exporting any other cosmetic items.

![Screenshot 2021-11-09 155245](https://user-images.githubusercontent.com/1069322/141002877-9b7d2fd0-7982-4830-b89f-9965780d08b3.jpg)

This is low priority, but maybe someone could help me debug this.

**Comment by angelic-knight** [comment]
Step 1: Search code base for the string "Required extra info for item" and find it at `item.py:3726`.
Realize that it's failing because f(...) is returning false.
Read that f is a function from the list of functions found in `_cls_map` for "Microtransaction".
See that item class "Microtransaction" uses `_type_currency` and `_type_microtransaction`.
So this is probably very related to the line above. I tweaked the error message for it so it prints out the rowid of the item from BaseItemType.dat
![image](https://user-images.githubusercontent.com/89628672/141057374-677d3c91-d155-4d86-b359-159b9e242cc5.png)
We see that Currency Cyclone Effect is at line 3508.
Then in [the dat viewer](https://snosme.github.io/poe-dat-viewer/), we can look at CurrencyItems.dat and see if there's any row that points to BaseItemType key 3508.
There isn't.
Therefore PyPoE's assumption that all Microtransaction class items will have an entry in CurrencyItems.dat is wrong and needs some kind of fixing.
